### ISSUE TITLE
Averaging weights in gram-cam.py

### ISSUE THREAD

**Issue by jinchenglee** [jacobgil/keras-grad-cam#5]
Line 47:    weights = np.mean(grads_val, axis = (0, 1))

Hi, Jacob. 

Why do you do average before multiplying weights to conv_outputs so that per conv filter only multiply to a single "averaged" weight? 

If I understand the paper correctly, it would be more accurate we directly do element-wise multiplication between weights of every pixel of every conv filter output to the filter output, then average over number of filters to get gradients-activation-map. Am I understanding it wrong?

[My code](https://github.com/jinchenglee/CarND-Behavioral-Cloning/blob/master/cam.py) looks sth. like this:

`    width, height, _ = original_img.shape

    img_rgb = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)

    img = normalize_color(img_rgb[None,:,:,:])
    img = img.reshape([1,66,200,3])

    conv_outputs, grads_val, angle = gradients_function([img])
    conv_outputs, grads_val = conv_outputs[0,:], grads_val[0,:,:,:]

    # Evaluate the angle to determine the weights
    class_weights = grad_cam_loss(grads_val, angle) # function to convert steering angle to weigts

    #Create the class activation map.
    cam = np.zeros(dtype = np.float32, shape = conv_outputs.shape)

    # Element-wise muliplication
    cam = class_weights*conv_outputs

    cam = np.mean(cam, axis = (2)) # Average between all filters

    cam /= np.max(cam)
    cam = cv2.resize(cam, (height, width))
    heatmap = cv2.applyColorMap(np.uint8(255*cam), cv2.COLORMAP_JET)
`

**Comment by jacobgil** [comment]
Hi @jinchenglee, nice project.

I think that if you look at equation (3) in page 4 in the paper, the gradients with respect to each conv layer are spatially averaged for each feature map i. 
Is there a chance you were confusing w_c_k in equation (1), that is used in case of regular CAM?

Here is another way to verify that the result is like in the paper.
They state that in case of a model that has global average pooling + a dense layer, the output of grad-cam and that of the older CAM algorithm is identical (when creating visualizations for the last conv layer). Grad-CAM is designed to have this property.
In case of the older CAM visualization, the weight w_i at index i in the final dense layer, corresponding to some class C, is used to multiply A_i - the conv layer output, before the global average pooling.
Now lets look at grad-cam, when using this same architecture.
The gradient of the loss L with respect to A_i in the feature map, is w_i, since the loss is a sum over w_i * A_i.
The spatial average of the gradients for all the pixels, is also w_i (since the gradient is identical for every pixel).
Therefore grad-cam and cam have the same result in this case.
